### ISSUE TITLE
Form fields are using wrong default unit (always using STANDARD_UNIT)

### ISSUE THREAD

**Issue by ipsod** [coddingtonbear/django-measurement#30] opened 2016-06-21 18:46 UTC
I've set up my form like this:

```
class ThingForm(forms.ModelForm):

    height = MeasurementField(
        measurement=Distance,
        unit_choices=(('inch', 'in'), ('cm', 'cm'), ('feet', 'ft'), ('m', 'm')),
    )
    diameter = MeasurementField(
        measurement=Distance,
        unit_choices=(('inch', 'in'), ('cm', 'cm'), ('feet', 'ft'), ('m', 'm')),
    )
```

The form recognizes `unit_choices`, as those are the choices I get, but it defaults to meters instead of inches.  In `django_measurements/models.py`, it seems like the method `MeasurementField.get_default_unit()` should return `inch`, but the `if unit_choices` never evaluates as true, and `self.widget_args['unit_choices']` seems to be empty no matter what.

I'm using Python 3.5 and Django 1.9.

**Comment by codingjoe** [comment] 2016-06-23 14:16
Hm... I agree that we should hold up the metric system. I didn't get the problem entirely tho. Do you have a couple of lines to reproduce your issue?

**Comment by SOMGER** [comment] 2018-02-26 05:10
Hi, I face the same problem when creating a form from a model with a weight MeasurementField. My DetailsView has the correct default  unit  which is 'kg'; but my UpdateView converts values to 'lb' in the form displayed to edit values. Any ideas on how to fix this?

**Comment by codingjoe** [comment] 2018-03-10 16:49
@SOMGER no I don't. You don't happen to have a small example app? I'd really like to debug this one.

**Comment by SOMGER** [comment] 2018-03-10 17:43
@codingjoe I am quite a newbie, so I don't have one. But I will try to set up sth shortly. For a while it seemed to be fixed by re-running the migration every time I detected that the form displays lb instead of kg. but now it just converts to lb irrespective of running the migrations again.

**Comment by SOMGER** [comment] 2018-03-10 20:11
@codingjoe, as I was recreating the issue, what I realized is that the problem is caused by rendering the form template with django-bootstrap3, bootstrap_field option, or just simply by including
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

in the template, without them, everything works fine, once these are added, the form field is changed to lb instead of the default kg.

**Comment by codingjoe** [comment] 2018-03-22 09:19
@SOMGER Django 1.11 does have widget templates. I recommend to overwrite them to have nice looking forms and drop packages that work do strange magic ;)

**Closed by codingjoe** 2018-03-22 09:19 UTC

**Comment by SOMGER** [comment] 2018-03-22 13:52
@codingjoe  Thanks for the suggestion, and your time! Can you point me to some practical tutorials on those? Like I said, I am a newbie to programming. :) By the way, it was only the tag {% bootstrap_javascript %} that causes the problem, removing that only doesn't really changes the form display much; and everything works like charm now.

**Comment by codingjoe** [comment] 2018-03-22 14:41
@SOMGER 
This is how to configure how to override the templates:
https://docs.djangoproject.com/en/2.0/howto/overriding-templates/

Here is a list of all built in templates:
https://docs.djangoproject.com/en/2.0/ref/forms/widgets/#built-in-widgets
